### ISSUE TITLE
Missing data in chapter 10

### ISSUE THREAD

**Issue by mohmmadd** [RadarBook/software#3]
Hi
I can't run these files in chapter 10 by matlab or python because of data missing:
back_projection_cv_example
stripmap_cv_example
back_projection_backhoe_example
@BradleyClymer
@RadarBook

**Comment by BradleyClymer** [comment]
@RadarBook it looks like most of this data is available at `https://www.sdms.afrl.af.mil/index.php` -- makes sense that it wouldn't be publishable here both because of the size, and potentially because of export controls. 

@mohmmadd I added a pull request to README.md reflecting this, but please note that I am user like you rather a developer of this code, and probably should not be mentioned directly.

**Comment by mohmmadd** [comment]
@BradleyClymer Thanks for your attention.
Sorry, I was wrong because you were on the contribution list.

**Comment by RadarBook** [comment]
Sorry for my late response on this.  Thank you @BradleyClymer for responding!
